/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qeghmkWSZiC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Skeleton } from "@/components/ui/skeleton"

export function SkeletonList() {
  return (
    <div className="w-full mx-auto p-4 space-y-6">
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[70%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[70%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[65%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[70%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[80%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[70%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[80%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[70%] rounded-md" />
        </div>
      </div>
      <div className="flex items-center space-x-4 animate-pulse">
        <div className="space-y-2">
          <Skeleton className="h-4 w-24 rounded-md" />
          <Skeleton className="h-6 w-24 rounded-md" />
        </div>
        <div className="space-y-2 w-full">
          <Skeleton className="h-8 w-[90%] rounded-md" />
          <Skeleton className="h-8 w-[80%] rounded-md" />
        </div>
      </div>
    </div>
  );
}
